command: ['node', '.next/standalone/server.js']

env:
  - name: NODE_ENV
    value: production
  - name: PORT
    valueFrom: DATABRICKS_APP_PORT
  - name: AIM_CATALOG
    value: sales
  - name: ANTHROPIC_API_KEY
    valueFrom: anthropic_api_key_secret
  - name: DATABRICKS_SERVER_HOSTNAME
    value: adb-1291693653051285.5.azuredatabricks.net
  - name: DATABRICKS_HTTP_PATH
    value: /sql/1.0/warehouses/4bc2370478860bc8
  - name: DATABRICKS_WAREHOUSE_ID
    value: '4bc2370478860bc8'